# Generated by Django 3.2.15 on 2022-09-27 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('eye', 'Eye'), ('hair', 'Hair')], max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, upload_to='organ_pics')),
                ('desc', models.TextField()),
            ],
            options={
                'verbose_name': 'organ',
                'verbose_name_plural': 'organs',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='VeganFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('image', models.ImageField(upload_to='food_pics')),
                ('desc', models.TextField()),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veganapp.organ')),
            ],
            options={
                'verbose_name': 'food',
                'verbose_name_plural': 'foods',
                'ordering': ('name',),
            },
        ),
    ]
