# Generated by Django 3.2.15 on 2022-10-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veganapp', '0002_alter_organ_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organ',
            options={'ordering': ['name'], 'verbose_name': 'organ', 'verbose_name_plural': 'organs'},
        ),
        migrations.AlterModelOptions(
            name='veganfood',
            options={'ordering': ['name'], 'verbose_name': 'food', 'verbose_name_plural': 'foods'},
        ),
        migrations.AlterField(
            model_name='veganfood',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food_pics'),
        ),
    ]
