# Generated by Django 3.2.15 on 2022-10-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veganapp', '0003_auto_20221002_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veganfood',
            name='image',
            field=models.ImageField(blank=True, default='image', upload_to='food_pics'),
            preserve_default=False,
        ),
    ]
